# 服务配置
# spring配置
# 1.应用配置
# 2.数据库连接池
# 3.JPA
server:
  port: 9003
spring:
  application:
    name: ihrm-recruitment #指定服务名

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 5201314a

  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true